language: node_js
node_js:
  - "6.9"
sudo: false
branches:
  only:
    - master
install:
- npm install
script:
- npm run build
after_success:
- bash ./travis-deploy.sh
env:
  global:
    - GITHUB_REPO: tscanlin/blog.timscanlin.net
    - secure: j/r6YA/PGMuhmE7bQJ5D0qzbwwcIkjuvEviLXo3YHAimp993QBNQ/FmzQQmi9mQ/Sq/1k3cO2Eum7lNtGd099IlDLJ9CrMUbj4JqY0zibZdvysEBcg97hT0Qw8+7qrFtdrM8tMyzSmAGy1BAg5RGIMpo5wLk2932E7Py7MuL+KeIrf6bNkghqWyYpC5ve/iM/DX4Hh+GE3f44mW1bhViSVSnkYlTuLd9X8HPxIL0K2egc4UA1jS5aQ5ux8eWKwuhCDF/LtLAG9SFqslCJHRYgYHzhcax+p+Tv5qqPKKPiIbP80dtAaDBLvkdWeYl7fqLa+bBw0BNV9lbf0/luysNR6vMLv1wEbnG6LDqBMDrzge5yLg3LeWhdq+IlV87yhg7cIQIkh+314jCVo0vr6igHnrMThyRk74/znrtgpFeAz/uRMIKYiLibgiRS6QVr1jqWP8Ebs28NJUunyACTD9VDcv4XW8YTxlWHBz6aY66Tf7IlpY0HqCf06QpYadecWeeLwne2VTsaADaZJZ8ePh35tvlSvl+ahSWB7hNqrCV8aTWD2YvfgNXoVOK7jt822uhR1Ahm7vlb/fbuDo6KKlaRGEC41tPw4TGLOia2hNyoW6QUbtiP4UkTPhba+BcdSsiydkE7Au7xU8Z0lxGbl97tzEuPpuokfFgTtxw4L7Rl6Y=
